### ISSUE TITLE
t/dir.t test 6 (readdir after opendir)

### ISSUE THREAD

**Issue by toddr** [CpanelInc/Test-MockFile#13]
We have a test that confirms actual perl directory read behavior is that directories created after opendir are not seen when at EOF and doing a readdir. 

This seems to be breaking only on freebsd for the moment.

http://matrix.cpantesters.org/?dist=Test-MockFile%200.008;os=freebsd;reports=1

**Comment by toddr** [comment]
@eserte FYI I saw the failures. I don't have a plan for this other than maybe to skip the test. I'm going to ask p5p if they're aware of anything related to this.

**Comment by eserte** [comment]
The special things about the failing smokers: ZFS is used here. It does not fail on my other FreeBSD smokers with traditional UFS.

**Comment by toddr** [comment]
The problem is that the behavior of readdir is somewhat undefined and left to the OS. I'm probably going to just remove the test and stick with my current behavior.

**Comment by toddr** [comment]
Should be fixed by 6c7dbfa5c64260af7d86070bbc2a53387fcd8b2a
