### ISSUE TITLE
Bizarre copy of ARRAY in list assignment with File::Find

### ISSUE THREAD

**Issue by atoomic** [CpanelInc/Test-MockFile#23]
This could be a bug in Overload::FileCheck not sure at this time

```perl
use Test::MockFile;
use File::Find;

sub f {

    my @list;
    File::Find::find(
        {   no_chdir => 1,
            wanted   => sub { }
        },
        '/dir'
    );

    return \@list;
}

my @a;
push @a, @{ f() };
```

this is raising a warning from Overload::FileCheck
```
Bizarre copy of ARRAY in list assignment at /usr/local/cpanel/3rdparty/perl/528/lib/perl5/cpanel_lib/x86_64-linux-64int/Overload/FileCheck.pm line 579.
```

**Comment by toddr** [comment]
I can't reproduce this error at all. Did you fix it in Overload::FileCheck?

**Comment by atoomic** [comment]
This clearly looks a problem on Overload::FileCheck, cannot remember which commit really fixed it
probably a bisect will point to it.

This is fine closing it if we cannot reproduce it

**Comment by toddr** [comment]
This was a result of an issue in Overload::FileCheck: https://github.com/CpanelInc/Overload-FileCheck/issues/9
