### ISSUE TITLE
Provide one helper to get the filename '->filename'

### ISSUE THREAD

**Issue by atoomic** [CpanelInc/Test-MockFile#31]
When mocking multiple files like this
```perl
my @mocked_files = map { Test::MockFile->file( $_ ) } @files;
```

Having one additional helper to get the filename would be useful 
```perl
say $_->filename for @mocked_files
```

**Comment by toddr** [comment]
yep. For the moment `$_->{'file_name'}` would work

**Comment by toddr** [comment]
Resolved in master. Will be in next release.
