### ISSUE TITLE
SEEK does not return the new position.

### ISSUE THREAD

**Issue by squareplanetdesign** [CpanelInc/Test-MockFile#49]
When testing a module that includes sysseek() the SEEK() method was returning 1 on success like seek(), but this breaks sysseek() since it expects SEEK() to return the new position, not success or failure.

Here is an example that illustrates the problem:

```
perl -e '
use Test::More;
use Test::MockFile;

my $mock = Test::MockFile->file("/fake", "hello world");
if (open(my $fh, "<", "/fake")) {
    ok seek($fh, 6, 0), "seek returns truthful when successful.";
    is sysseek($fh, 6, 0), 6, "sysseek returns new position when successful.";
}
'
```

The second assertion fails since SEEK return 1 no matter what position you seek. It seems like it need to return the new position in addition to setting the new position.

**Comment by toddr** [comment]
I can fix this everywhere but seek 0. tie doesn't have a solution for this :\

**Comment by toddr** [comment]
I could probably override sysseek but that's a significant change.

**Comment by toddr** [comment]
Actually... "0 but true" to the rescue!

**Comment by toddr** [comment]
This will be in the next release.
